import React, { useState } from "react";
import {InfiniteScroll} from "react-infinite-scroll-component";
import { Avatar, Divider, List, Skeleton } from "antd";
const Tea_stu_card = () => {
  const [data, setData] = useState([
    "Kaiya",
    "Lucinda",
    "Axl",
    "Jaziah",
    "Bodhi",
    "Nico",
    "Jasmine",
    "Selah",
    "Elias",
    "Zuri",
    "Marcel",
    "Callie",
    "Rosie",
    "Lea",
    "Jasper",
    "Kash",
    "Reagan",
    "Mira",
    "Jett",
    "Koda",
    "Mikayla",
    "Coraline",
    "Aniya",
    "Kamryn",
    "Toby",
    "Levi",
    "Maren",
    "Aurelia",
    "Darian",
    "Brycen",
    "Emmy",
    "Harrison",
    "Anaya",
    "Saylor",
    "Amira",
    "Livia",
    "Lyla",
    "Hazel",
    "Eleanor",
    "Isaiah",
    "Cali",
    "Khalil",
    "Elliana",
    "Maliah",
    "Alfred",
    "Dwayne",
    "Arden",
    "Finnegan",
    "Kade",
    "Edgar",
    "Malcolm",
    "Jacqueline",
    "Esmeralda",
    "Chanel",
    "Augustus",
    "Reuben",
    "Brennan",
    "Cayson",
    "Riley",
    "Paxton",
    "Kamila",
    "Hattie",
    "Landon",
    "Arian",
    "Zaiden",
    "Jovani",
    "Rosalie",
    "Amaris",
    "Ryann",
    "Vihaan",
    "Remington",
    "Kaitlyn",
    "Thalia",
    "Jaden",
    "Rayna",
    "Jairo",
    "Maeve",
    "Leona",
    "Uriel",
    "Landon",
    "Giovanni",
    "Bryce",
    "Destiny",
    "Dayana",
    "Emmalyn",
    "Arabella",
    "Eliana",
    "Alexandria",
    "Zayne",
    "Delaney",
  ]);

  return (
    <>
      <div>
      
      </div>
    </>
  );
};

export default Tea_stu_card;
